#!/usr/bin/env python3
"""
Router classifier training script.

Usage:
  1. Put one message per line in:
       scripts/data/instant.txt   (e.g. "What's the capital of France?")
       scripts/data/reasoning.txt (e.g. "Prove that sqrt(2) is irrational.")
  2. Run:  python scripts/train_router.py
  3. Output: src/classifier/router.ts  (drop-in replacement for the heuristic)

Requirements:
  pip install scikit-learn numpy
"""

import json
import re
import sys
from pathlib import Path

try:
    import numpy as np
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.linear_model import LogisticRegression
    from sklearn.model_selection import cross_val_score
    from sklearn.pipeline import Pipeline
except ImportError:
    sys.exit("Missing dependencies. Run: pip install scikit-learn numpy")

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).parent
DATA_DIR = SCRIPT_DIR / "data"
OUT_FILE = SCRIPT_DIR.parent / "src" / "classifier" / "router.ts"

INSTANT_FILE = DATA_DIR / "instant.txt"
REASONING_FILE = DATA_DIR / "reasoning.txt"

# ---------------------------------------------------------------------------
# Load data
# ---------------------------------------------------------------------------
def load_lines(path: Path) -> list[str]:
    lines = [l.strip() for l in path.read_text(encoding="utf-8").splitlines()]
    return [l for l in lines if l and not l.startswith("#")]

print("Loading data…")
instant_texts = load_lines(INSTANT_FILE)
reasoning_texts = load_lines(REASONING_FILE)

print(f"  Instant   : {len(instant_texts)} samples")
print(f"  Reasoning : {len(reasoning_texts)} samples")

if len(instant_texts) < 10 or len(reasoning_texts) < 10:
    sys.exit("Need at least 10 samples per class.")

texts  = instant_texts + reasoning_texts
labels = [0] * len(instant_texts) + [1] * len(reasoning_texts)

# ---------------------------------------------------------------------------
# Train
# ---------------------------------------------------------------------------
print("\nTraining TF-IDF + Logistic Regression…")

vectorizer = TfidfVectorizer(
    analyzer="word",
    token_pattern=r"(?u)\b\w+\b",
    ngram_range=(1, 2),       # unigrams + bigrams
    max_features=512,         # vocab cap — keeps TS file small
    sublinear_tf=True,
    min_df=2,
)

clf = LogisticRegression(C=1.0, max_iter=1000, solver="lbfgs")

# Cross-validate before fitting on full data
X = vectorizer.fit_transform(texts)
scores = cross_val_score(clf, X, labels, cv=5, scoring="accuracy")
print(f"  5-fold CV accuracy: {scores.mean():.3f} ± {scores.std():.3f}")

clf.fit(X, labels)

# ---------------------------------------------------------------------------
# Extract weights
# ---------------------------------------------------------------------------
vocab: dict[str, int] = vectorizer.vocabulary_          # term → col index
idf: np.ndarray       = vectorizer.idf_                 # shape (n_features,)
coef: np.ndarray      = clf.coef_[0]                    # shape (n_features,)
bias: float           = float(clf.intercept_[0])

# Combined weight: idf * coef  (so inference is just dot(tf_vec, weights) + bias)
weights: np.ndarray = idf * coef                        # shape (n_features,)

# Build term→weight map, drop near-zero entries to save space
THRESHOLD = 1e-4
term_weights: dict[str, float] = {
    term: float(weights[idx])
    for term, idx in vocab.items()
    if abs(weights[idx]) > THRESHOLD
}

print(f"  Non-zero terms after pruning: {len(term_weights)}")

# ---------------------------------------------------------------------------
# Emit TypeScript
# ---------------------------------------------------------------------------
OUT_FILE.parent.mkdir(parents=True, exist_ok=True)

# Sort by absolute weight for readability
sorted_terms = sorted(term_weights.items(), key=lambda kv: abs(kv[1]), reverse=True)

lines: list[str] = []
lines.append("// AUTO-GENERATED by scripts/train_router.py — do not edit by hand.")
lines.append("// Logistic Regression + TF-IDF router: returns 'reasoning' | 'instant'")
lines.append("")
lines.append(f"const BIAS = {bias:.6f};")
lines.append("")
lines.append("// term → combined weight  (idf * lr_coef)")
lines.append("// Positive weight → reasoning,  Negative → instant")
lines.append("const WEIGHTS: Record<string, number> = {")
for term, w in sorted_terms:
    escaped = term.replace("\\", "\\\\").replace('"', '\\"')
    lines.append(f'  "{escaped}": {w:.6f},')
lines.append("};")
lines.append("")
lines.append("function tokenize(text: string): string[] {")
lines.append("  const lower = text.toLowerCase();")
lines.append("  const tokens: string[] = lower.match(/\\b\\w+\\b/g) ?? [];")
lines.append("  // bigrams")
lines.append("  const out = [...tokens];")
lines.append("  for (let i = 0; i < tokens.length - 1; i++) {")
lines.append('    out.push(tokens[i] + " " + tokens[i + 1]);')
lines.append("  }")
lines.append("  return out;")
lines.append("}")
lines.append("")
lines.append("export function classify(text: string): 'reasoning' | 'instant' {")
lines.append("  const tokens = tokenize(text);")
lines.append("  // TF (raw count / total tokens)")
lines.append("  const tf: Record<string, number> = {};")
lines.append("  for (const t of tokens) {")
lines.append("    tf[t] = (tf[t] ?? 0) + 1 / tokens.length;")
lines.append("  }")
lines.append("  let score = BIAS;")
lines.append("  for (const [term, weight] of Object.entries(tf)) {")
lines.append("    if (term in WEIGHTS) score += tf[term] * WEIGHTS[term];")
lines.append("  }")
lines.append("  // sigmoid > 0.5  ⟺  score > 0")
lines.append("  return score > 0 ? 'reasoning' : 'instant';")
lines.append("}")
lines.append("")

OUT_FILE.write_text("\n".join(lines), encoding="utf-8")
print(f"\nWrote {OUT_FILE}")
print("Done! Now update src/hooks/useWebLLM.ts to import { classify } from '../classifier/router'")
print("and replace routeMessage(text) with classify(text).")
